// Auto-generated bridge configuration
#pragma once

#include <string>
#include <vector>
#include <rclcpp/rclcpp.hpp>
#include <rclcpp/qos.hpp>

struct TopicParams {
    std::string ros1_type_name;
    std::string ros2_type_name;
    std::string topic_name;
    size_t queue_size;
    rclcpp::QoS publisher_qos;
};

enum BridgeDirection {
    ROS1_TO_ROS2,
    ROS2_TO_ROS1
};

struct ServiceParams {
    std::string service_name;
    std::string type_name;
    BridgeDirection direction;
};

const std::vector<TopicParams> TOPICS = {
    {
        "std_msgs/Bool",
        "std_msgs/msg/Bool",
        "service_manager/design_mode_status",
        1,
        rclcpp::SystemDefaultsQoS()
    },{
        "gmr_gui_msgs/SessionInfo",
        "gmr_gui_msgs/msg/SessionInfo",
        "/guiPlugin/session_info",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "gmr_gui_msgs/GuiCmd",
        "gmr_gui_msgs/msg/GuiCmd",
        "/coordinator/gui_cmd",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "gmr_gui_msgs/GuiCmd",
        "gmr_gui_msgs/msg/GuiCmd",
        "/follower_1/coordinator/gui_cmd",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "gmr_gui_msgs/SeverityMsg",
        "gmr_gui_msgs/msg/SeverityMsg",
        "/general/show_message_request",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/UInt8",
        "std_msgs/msg/UInt8",
        "/remote_system/updt_event",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "gmr_gui_msgs/SeverityMsg",
        "gmr_gui_msgs/msg/SeverityMsg",
        "/follower_1/general/show_message_request",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "gmr_gui_msgs/GuiCmd",
        "gmr_gui_msgs/msg/GuiCmd",
        "/coordinator/fast_gui_cmd",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "gmr_gui_msgs/MvExt",
        "gmr_gui_msgs/msg/MvExt",
        "/coordinator/move_ext_cmd_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "gmr_gui_msgs/MvExt",
        "gmr_gui_msgs/msg/MvExt",
        "/follower_1/coordinator/move_ext_cmd_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/UInt8",
        "std_msgs/msg/UInt8",
        "/coordinator/purge_compound",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/UInt8",
        "std_msgs/msg/UInt8",
        "/coordinator/overpressure_routine",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/Empty",
        "std_msgs/msg/Empty",
        "/coordinator/change_polish_pad",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/Bool",
        "std_msgs/msg/Bool",
        "/gui_plugin/pause_cmd",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "gmr_gui_msgs/GuiCmd",
        "gmr_gui_msgs/msg/GuiCmd",
        "/follower_1/right_plugin/gui_fdbk",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/Bool",
        "std_msgs/msg/Bool",
        "/right_plugin/switch_profile_mode",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/UInt16",
        "std_msgs/msg/UInt16",
        "/coordinator/change_sp_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/Empty",
        "std_msgs/msg/Empty",
        "/coordinator/apply_cpd_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/Bool",
        "std_msgs/msg/Bool",
        "/ui_manager/robot_led_fault",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/Bool",
        "std_msgs/msg/Bool",
        "/follower_1/ui_manager/robot_led_fault",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/Empty",
        "std_msgs/msg/Empty",
        "/guiPlugin/tool_change_recover",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/Int32",
        "std_msgs/msg/Int32",
        "/guiPlugin/manual_tool_change",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/Bool",
        "std_msgs/msg/Bool",
        "/left_plugin/enable_change_sandpaper",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "profile_msgs/ProfileSlimMsg",
        "profile_msgs/msg/ProfileSlimMsg",
        "/coordinator/gui_add_profile_info",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "profile_msgs/ProfileSlimMsg",
        "profile_msgs/msg/ProfileSlimMsg",
        "/coordinator/gui_edit_profile_info",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "profile_msgs/ProfileSlimMsg",
        "profile_msgs/msg/ProfileSlimMsg",
        "/coordinator/gui_copy_profile",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/String",
        "std_msgs/msg/String",
        "/coordinator/gui_delete_profile",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/Bool",
        "std_msgs/msg/Bool",
        "/left_plugin/customer_enable_left_panel",
        1,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/String",
        "std_msgs/msg/String",
        "/coordinator/gui_edit_profile",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/String",
        "std_msgs/msg/String",
        "/coordinator/gui_activate_profile",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/UInt16",
        "std_msgs/msg/UInt16",
        "/coordinator/mv_proc_sec_frwd_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/UInt16",
        "std_msgs/msg/UInt16",
        "/coordinator/mv_proc_sec_bkwd_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/String",
        "std_msgs/msg/String",
        "/coordinator/copy_proc_sec_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/String",
        "std_msgs/msg/String",
        "/coordinator/delete_proc_sec_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "profile_msgs/ProcSecMsg",
        "profile_msgs/msg/ProcSecMsg",
        "/coordinator/edit_proc_sec_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "profile_msgs/SectionTypeMsg",
        "profile_msgs/msg/SectionTypeMsg",
        "/coordinator/add_proc_sec_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "profile_msgs/SectionTypeMsg",
        "profile_msgs/msg/SectionTypeMsg",
        "/coordinator/add_non_proc_sec_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/UInt16",
        "std_msgs/msg/UInt16",
        "/coordinator/add_tool_change_sec_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "profile_msgs/ScanSecMsg",
        "profile_msgs/msg/ScanSecMsg",
        "/coordinator/edit_scan_sec_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/String",
        "std_msgs/msg/String",
        "/coordinator/copy_scan_sec_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/String",
        "std_msgs/msg/String",
        "/coordinator/delete_scan_sec_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/UInt16",
        "std_msgs/msg/UInt16",
        "/coordinator/mv_scan_sec_frwd_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/UInt16",
        "std_msgs/msg/UInt16",
        "/coordinator/mv_scan_sec_bkwd_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "gmr_msgs/Float64Array",
        "gmr_msgs/msg/Float64Array",
        "/coordinator/update_bbox_param_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "gmr_msgs/Float64Array",
        "gmr_msgs/msg/Float64Array",
        "/coordinator/confirm_bbox_param_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "profile_msgs/RobotPoseMsg",
        "profile_msgs/msg/RobotPoseMsg",
        "/coordinator/update_seed_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "gmr_msgs/UInt32Array",
        "gmr_msgs/msg/UInt32Array",
        "/coordinator/update_tool_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/Int32",
        "std_msgs/msg/Int32",
        "/coordinator/update_paper_count_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "gmr_gui_msgs/PlanRequest",
        "gmr_gui_msgs/msg/PlanRequest",
        "/coordinator/plan_request_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "profile_msgs/ProfileSlimMsg",
        "profile_msgs/msg/ProfileSlimMsg",
        "/coordinator/gui_finish_profile",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "profile_msgs/PPassAryMsg",
        "profile_msgs/msg/PPassAryMsg",
        "/coordinator/confirm_add_proc_sec",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "profile_msgs/PPassAryMsg",
        "profile_msgs/msg/PPassAryMsg",
        "/coordinator/confirm_edit_proc_sec",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "profile_msgs/PPassAryMsg",
        "profile_msgs/msg/PPassAryMsg",
        "/coordinator/pass_list_changed_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/UInt16",
        "std_msgs/msg/UInt16",
        "/coordinator/load_simulation_with_index",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/UInt16",
        "std_msgs/msg/UInt16",
        "/coordinator/changed_simulation_frame",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/String",
        "std_msgs/msg/String",
        "/coordinator/gui_activate_macro_profile",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "profile_msgs/MacroProfMsg",
        "profile_msgs/msg/MacroProfMsg",
        "/coordinator/gui_add_macro_profile",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "profile_msgs/MacroProfMsg",
        "profile_msgs/msg/MacroProfMsg",
        "/coordinator/gui_edit_macro_profile",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/String",
        "std_msgs/msg/String",
        "/coordinator/gui_delete_macro_profile",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/String",
        "std_msgs/msg/String",
        "/coordinator/gui_load_macro_profile",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/Empty",
        "std_msgs/msg/Empty",
        "/coordinator/compute_registration",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/Bool",
        "std_msgs/msg/Bool",
        "/guiPlugin/smart_retrieve",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "geometry_msgs/Pose",
        "geometry_msgs/msg/Pose",
        "/visualization/load_tcp",
        1,
        rclcpp::SystemDefaultsQoS()
    }
};

const std::vector<ServiceParams> SERVICES = {
    {
        "/coordinator/load_multi_profile",
        "gmr_gui_msgs/srv/LoadMultiProfile",
        ROS2_TO_ROS1
    },
    {
        "/coordinator/refill_compound",
        "std_srvs/srv/SetBool",
        ROS2_TO_ROS1
    },
    {
        "/coordinator/set_door_unlock",
        "std_srvs/srv/SetBool",
        ROS2_TO_ROS1
    },
    {
        "/ui_manager/readiness_check",
        "srv_manager_msgs/srv/SystemCheck",
        ROS2_TO_ROS1
    },
    {
        "/ui_manager/readiness_check",
        "srv_manager_msgs/srv/SystemCheck",
        ROS2_TO_ROS1
    },
    {
        "/coordinator/gui_query_robot_pose",
        "MoMe/srv/BotPoseQry",
        ROS2_TO_ROS1
    },
    {
        "/ui_manager/start_smart_retrieve",
        "gmr_gui_msgs/srv/SmartRetrieveState",
        ROS2_TO_ROS1
    },
    {
        "/coordinator/set_door_unlock",
        "std_srvs/srv/SetBool",
        ROS2_TO_ROS1
    },
    {
        "/rightPlugin/popup_safeguard_recover_panel",
        "std_srvs/srv/SetBool",
        ROS1_TO_ROS2
    },
    {
        "/gui_plugin/popup_chng_sp_intrp_panel",
        "gmr_msgs/srv/SetString",
        ROS1_TO_ROS2
    },
    {
        "/gui_plugin/popup_reload_panel",
        "std_srvs/srv/Trigger",
        ROS1_TO_ROS2
    },
    {
        "/gui_plugin/overpressure_warning",
        "std_srvs/srv/Trigger",
        ROS1_TO_ROS2
    },
    {
        "/gui_plugin/pad_change_panel",
        "gmr_msgs/srv/ToggleUInt8",
        ROS1_TO_ROS2
    },
    {
        "/gui_plugin/popup_manual_tool_change_panel",
        "gmr_msgs/srv/ToggleUInt8",
        ROS1_TO_ROS2
    },
    {
        "/gui_plugin/popup_checkpoint_decision_panel",
        "gmr_gui_msgs/srv/GetUserCheckPointDecision",
        ROS1_TO_ROS2
    },
    {
        "/gui_plugin/afd_bottom_out_warning",
        "std_srvs/srv/Trigger",
        ROS1_TO_ROS2
    },
    {
        "/workspace_manager/get_chng_sp_user_opt",
        "multi_robot_msgs/srv/GetUsrOpt",
        ROS1_TO_ROS2
    },
    {
        "/right_plugin/update_profile_list",
        "gmr_gui_msgs/srv/UpdtProfList",
        ROS1_TO_ROS2
    },
    {
        "/right_plugin/gui_fdbk",
        "gmr_gui_msgs/srv/GuiFdbk",
        ROS1_TO_ROS2
    },
    {
        "/right_plugin/reset_tool_view",
        "std_srvs/srv/Trigger",
        ROS1_TO_ROS2
    },
    {
        "/right_plugin/set_tool_view",
        "gmr_msgs/srv/SetString",
        ROS1_TO_ROS2
    },
    {
        "/follower_1/right_plugin/reset_tool_view",
        "std_srvs/srv/Trigger",
        ROS1_TO_ROS2
    },
    {
        "/follower_1/right_plugin/set_tool_view",
        "gmr_msgs/srv/SetString",
        ROS1_TO_ROS2
    }
};
