#pragma once

#include <string>
#include <vector>

#include <rclcpp/rclcpp.hpp>
#include <rclcpp/qos.hpp>

struct TopicParams {
    std::string ros1_type_name;
    std::string ros2_type_name;
    std::string topic_name;
    size_t queue_size;
    rclcpp::QoS publisher_qos;
};

enum BridgeDirection {
    ROS1_TO_ROS2,
    ROS2_TO_ROS1
};

struct ServiceParams {
    std::string service_name;
    std::string type_name;
    BridgeDirection direction;
};

std::vector<TopicParams> TOPICS = {
    {
        "std_msgs/String",
        "std_msgs/msg/String",
        "chatter",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "gmr_gui_msgs/GuiCmd",
        "gmr_gui_msgs/msg/GuiCmd",
        "/coordinator/gui_cmd",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "gmr_gui_msgs/SeverityMsg",
        "gmr_gui_msgs/msg/SeverityMsg",
        "/general/show_message_request",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "gmr_gui_msgs/GuiCmd",
        "gmr_gui_msgs/msg/GuiCmd",
        "/coordinator/fast_gui_cmd",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "gmr_gui_msgs/MvExt",
        "gmr_gui_msgs/msg/MvExt",
        "/coordinator/move_ext_cmd_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/UInt8",
        "std_msgs/msg/UInt8",
        "/coordinator/purge_compound",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/UInt8",
        "std_msgs/msg/UInt8",
        "/coordinator/overpressure_routine",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/Empty",
        "std_msgs/msg/Empty",
        "/coordinator/change_polish_pad",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/Bool",
        "std_msgs/msg/Bool",
        "/gui_plugin/pause_cmd",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/Bool",
        "std_msgs/msg/Bool",
        "/right_plugin/switch_profile_mode",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/UInt16",
        "std_msgs/msg/UInt16",
        "/coordinator/change_sp_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/Empty",
        "std_msgs/msg/Empty",
        "/coordinator/apply_cpd_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "gmr_gui_msgs/GuiCmd",
        "gmr_gui_msgs/msg/GuiCmd",
        "/coordinator/gui_cmd",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "gmr_gui_msgs/MvExt",
        "gmr_gui_msgs/msg/MvExt",
        "/coordinator/move_ext_cmd_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/UInt8",
        "std_msgs/msg/UInt8",
        "/coordinator/purge_compound",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/UInt8",
        "std_msgs/msg/UInt8",
        "/coordinator/overpressure_routine",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/Empty",
        "std_msgs/msg/Empty",
        "/coordinator/change_polish_pad",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "gmr_gui_msgs/GuiCmd",
        "gmr_gui_msgs/msg/GuiCmd",
        "/coordinator/fast_gui_cmd",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "gmr_gui_msgs/SeverityMsg",
        "gmr_gui_msgs/msg/SeverityMsg",
        "/general/show_message_request",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/Bool",
        "std_msgs/msg/Bool",
        "/left_plugin/enable_change_sandpaper",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "gmr_gui_msgs/GuiCmd",
        "gmr_gui_msgs/msg/GuiCmd",
        "/coordinator/fast_gui_cmd",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "profile_msgs/ProfileSlimMsg",
        "profile_msgs/msg/ProfileSlimMsg",
        "/coordinator/gui_add_profile_info",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "profile_msgs/ProfileSlimMsg",
        "profile_msgs/msg/ProfileSlimMsg",
        "/coordinator/gui_edit_profile_info",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "profile_msgs/ProfileSlimMsg",
        "profile_msgs/msg/ProfileSlimMsg",
        "/coordinator/gui_copy_profile",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/String",
        "std_msgs/msg/String",
        "/coordinator/gui_delete_profile",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/Bool",
        "std_msgs/msg/Bool",
        "/left_plugin/customer_enable_left_panel",
        1,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/String",
        "std_msgs/msg/String",
        "/coordinator/gui_edit_profile",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/String",
        "std_msgs/msg/String",
        "/coordinator/gui_activate_profile",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/UInt16",
        "std_msgs/msg/UInt16",
        "/coordinator/mv_proc_sec_frwd_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/UInt16",
        "std_msgs/msg/UInt16",
        "/coordinator/mv_proc_sec_bkwd_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/String",
        "std_msgs/msg/String",
        "/coordinator/copy_proc_sec_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/String",
        "std_msgs/msg/String",
        "/coordinator/delete_proc_sec_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "profile_msgs/ProcSecMsg",
        "profile_msgs/msg/ProcSecMsg",
        "/coordinator/edit_proc_sec_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "profile_msgs/SectionTypeMsg",
        "profile_msgs/msg/SectionTypeMsg",
        "/coordinator/add_proc_sec_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "profile_msgs/SectionTypeMsg",
        "profile_msgs/msg/SectionTypeMsg",
        "/coordinator/add_non_proc_sec_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/UInt16",
        "std_msgs/msg/UInt16",
        "/coordinator/add_tool_change_sec_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "profile_msgs/ScanSecMsg",
        "profile_msgs/msg/ScanSecMsg",
        "/coordinator/edit_scan_sec_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/String",
        "std_msgs/msg/String",
        "/coordinator/copy_scan_sec_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/String",
        "std_msgs/msg/String",
        "/coordinator/delete_scan_sec_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/UInt16",
        "std_msgs/msg/UInt16",
        "/coordinator/mv_scan_sec_frwd_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/UInt16",
        "std_msgs/msg/UInt16",
        "/coordinator/mv_scan_sec_bkwd_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "gmr_msgs/Float64Array",
        "gmr_msgs/msg/Float64Array",
        "/coordinator/update_bbox_param_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "gmr_msgs/Float64Array",
        "gmr_msgs/msg/Float64Array",
        "/coordinator/confirm_bbox_param_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "profile_msgs/RobotPoseMsg",
        "profile_msgs/msg/RobotPoseMsg",
        "/coordinator/update_seed_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "gmr_msgs/UInt32Array",
        "gmr_msgs/msg/UInt32Array",
        "/coordinator/update_tool_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/Int32",
        "std_msgs/msg/Int32",
        "/coordinator/update_paper_count_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "gmr_gui_msgs/PlanRequest",
        "gmr_gui_msgs/msg/PlanRequest",
        "/coordinator/plan_request_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "profile_msgs/ProfileSlimMsg",
        "profile_msgs/msg/ProfileSlimMsg",
        "/coordinator/gui_finish_profile",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "profile_msgs/PPassAryMsg",
        "profile_msgs/msg/PPassAryMsg",
        "/coordinator/confirm_add_proc_sec",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "profile_msgs/PPassAryMsg",
        "profile_msgs/msg/PPassAryMsg",
        "/coordinator/confirm_edit_proc_sec",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "profile_msgs/PPassAryMsg",
        "profile_msgs/msg/PPassAryMsg",
        "/coordinator/pass_list_changed_from_gui",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/UInt16",
        "std_msgs/msg/UInt16",
        "/coordinator/load_simulation_with_index",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/UInt16",
        "std_msgs/msg/UInt16",
        "/coordinator/changed_simulation_frame",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/String",
        "std_msgs/msg/String",
        "/coordinator/gui_activate_macro_profile",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "profile_msgs/MacroProfMsg",
        "profile_msgs/msg/MacroProfMsg",
        "/coordinator/gui_add_macro_profile",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "profile_msgs/MacroProfMsg",
        "profile_msgs/msg/MacroProfMsg",
        "/coordinator/gui_edit_macro_profile",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/String",
        "std_msgs/msg/String",
        "/coordinator/gui_delete_macro_profile",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/String",
        "std_msgs/msg/String",
        "/coordinator/gui_load_macro_profile",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "std_msgs/Empty",
        "std_msgs/msg/Empty",
        "/coordinator/compute_registration",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "gmr_gui_msgs/GuiCmd",
        "gmr_gui_msgs/msg/GuiCmd",
        "/coordinator/fast_gui_cmd",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "gmr_gui_msgs/GuiCmd",
        "gmr_gui_msgs/msg/GuiCmd",
        "/coordinator/fast_gui_cmd",
        10,
        rclcpp::SystemDefaultsQoS()
    },
    {
        "gmr_gui_msgs/GuiCmd",
        "gmr_gui_msgs/msg/GuiCmd",
        "/coordinator/fast_gui_cmd",
        10,
        rclcpp::SystemDefaultsQoS()
    }
};

std::vector<ServiceParams> SERVICES = {
    {
        "add_two_ints",
        "example_interfaces/srv/AddTwoInts",
        ROS1_TO_ROS2
    }
};